In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
### Vocabulary size
voc_size=10000

## One Hot Representation

In [8]:
onehot_repr=[one_hot(words,voc_size) for words in sent] 
print(onehot_repr)

[[3098, 1392, 6568, 6048], [3098, 1392, 6568, 8880], [3098, 1927, 6568, 8177], [8041, 999, 3197, 8455, 5088], [8041, 999, 3197, 8455, 6225], [7210, 3098, 4773, 6568, 2826], [1411, 1617, 4534, 8455]]


## Word Embedding

In [9]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [10]:
import numpy as np

In [12]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='post',maxlen=sent_length)
print(embedded_docs)

[[3098 1392 6568 6048    0    0    0    0]
 [3098 1392 6568 8880    0    0    0    0]
 [3098 1927 6568 8177    0    0    0    0]
 [8041  999 3197 8455 5088    0    0    0]
 [8041  999 3197 8455 6225    0    0    0]
 [7210 3098 4773 6568 2826    0    0    0]
 [1411 1617 4534 8455    0    0    0    0]]


In [13]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [15]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 350ms/step
[[[-0.04255097 -0.03391864 -0.04573984  0.00488638  0.04470361
   -0.02987733  0.00135871  0.03543052 -0.0339423  -0.03759031]
  [-0.00915523 -0.01401579  0.01718007 -0.04659224  0.03443744
    0.01154651 -0.02690504 -0.00828173 -0.04954033 -0.00942404]
  [-0.01826794  0.02411017 -0.02836806 -0.0455575   0.01945008
   -0.03166751  0.01848172  0.02347006  0.00110666  0.02022047]
  [-0.04921364  0.0456551   0.04987751 -0.04408633 -0.02185689
    0.04692577  0.00941078  0.01408977  0.00149666  0.03761499]
  [-0.03356788  0.03013862  0.03049889 -0.00425371 -0.00425255
   -0.02775748 -0.00742003  0.0292037   0.01129172  0.01769567]
  [-0.03356788  0.03013862  0.03049889 -0.00425371 -0.00425255
   -0.02775748 -0.00742003  0.0292037   0.01129172  0.01769567]
  [-0.03356788  0.03013862  0.03049889 -0.00425371 -0.00425255
   -0.02775748 -0.00742003  0.0292037   0.01129172  0.01769567]
  [-0.03356788  0.03013862  0.03049889 -0.00425371 -0.0042

In [18]:
embedded_docs[0]

array([3098, 1392, 6568, 6048,    0,    0,    0,    0])

In [20]:
print(model.predict(embedded_docs[0]))
# converted into 10 dimensions

1/1 [==============================] - 0s 17ms/step
[[-0.04255097 -0.03391864 -0.04573984  0.00488638  0.04470361 -0.02987733
   0.00135871  0.03543052 -0.0339423  -0.03759031]
 [-0.00915523 -0.01401579  0.01718007 -0.04659224  0.03443744  0.01154651
  -0.02690504 -0.00828173 -0.04954033 -0.00942404]
 [-0.01826794  0.02411017 -0.02836806 -0.0455575   0.01945008 -0.03166751
   0.01848172  0.02347006  0.00110666  0.02022047]
 [-0.04921364  0.0456551   0.04987751 -0.04408633 -0.02185689  0.04692577
   0.00941078  0.01408977  0.00149666  0.03761499]
 [-0.03356788  0.03013862  0.03049889 -0.00425371 -0.00425255 -0.02775748
  -0.00742003  0.0292037   0.01129172  0.01769567]
 [-0.03356788  0.03013862  0.03049889 -0.00425371 -0.00425255 -0.02775748
  -0.00742003  0.0292037   0.01129172  0.01769567]
 [-0.03356788  0.03013862  0.03049889 -0.00425371 -0.00425255 -0.02775748
  -0.00742003  0.0292037   0.01129172  0.01769567]
 [-0.03356788  0.03013862  0.03049889 -0.00425371 -0.00425255 -0.02775748